# Generated by Django 3.1.7 on 2021-04-26 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210426_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 4, 5, 15, 64399, tzinfo=utc)),
        ),
    ]
